name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.15.7]
        otp: [26.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir and OTP
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache Mix dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: mix-deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: mix-deps-${{ runner.os }}-

      - name: Cache Mix build
        uses: actions/cache@v4
        with:
          path: _build
          key: mix-build-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: mix-build-${{ runner.os }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test

      - name: Run Docs Check
        run: mix docs