name: Publish to Hex

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: "1.15"
        otp-version: "26.2"

    - name: Install dependencies
      run: mix deps.get

    - name: Compile
      run: mix compile

    - name: Publish to Hex
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: mix hex.publish --yes